spring:
  datasource:
    url: jdbc:postgresql://0.0.0.0:5433/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
